version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: boost_gg_nginx_cont
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - boost-gg
  mongo:
    image: mongo:6
    container_name: boost-gg-mongo
    environment:
      MONGO_INITDB_DATABASE: boost-gg-mongo
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - boost-gg
    volumes:
      -  boostgg_mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "-u", "admin", "-p", "123456", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


  backend:
    build: ./server
    container_name: boost_gg_backend
    ports:
      - "5009:5009"
    env_file: ./server/.env
    networks:
      - boost-gg
    volumes:
      - uploads_data:/app/uploads
    depends_on:
        mongo:
         condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./client
    container_name: boost_gg_frontend
    ports:
      - "5179:5179"
    networks:
      - boost-gg
    env_file: ./client/.env
    depends_on:
      - backend

networks:
  boost-gg:
    driver: bridge

volumes:
  uploads_data:
   boostgg_mongo-data:
